api-version : 1.16
main: fr.stormer3428.warps.Warps
author: stormer3428
name: "StormerWarps"
softdepend: [Multiverse-Core]
api : []
version: 1.1.0-SNAPSHOT
load: POSTWORLD
commands:
  warp:
    description: "Teleports you to your warp"
  warps:
    description: "Lists all of your warps"
  setwarp:
    description: "Sets your warp"
  delwarp:
    description: "Deletes a warp"